- name: Cache NPM Dependencies
  uses: actions/cache@v4
  with:
    path: ~/.npm
    key: ${{ runner.os }}-node-${{ hashFile('**/package-lock.json) }}
    restore-keys: |
      ${{ runner.os }}-node-
